# Generated by Django 5.2.5 on 2025-09-22 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
        ('persona', '0002_alter_persona_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='oficina.oficina'),
        ),
    ]
